apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kortix
data:
  ENV_MODE: "production"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  DAYTONA_SERVER_URL: "https://app.daytona.io/api"
  DAYTONA_TARGET: "us"
  WEBHOOK_BASE_URL: "https://your-domain.com/api"
  LANGFUSE_HOST: "https://cloud.langfuse.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: kortix
data:
  NEXT_PUBLIC_ENV_MODE: "production"
  NEXT_PUBLIC_BACKEND_URL: "https://your-domain.com/api"
  NEXT_PUBLIC_URL: "https://your-domain.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: kortix
type: Opaque
stringData:
  # Supabase配置
  SUPABASE_URL: "YOUR_SUPABASE_URL"
  SUPABASE_ANON_KEY: "YOUR_SUPABASE_ANON_KEY"
  SUPABASE_SERVICE_ROLE_KEY: "YOUR_SUPABASE_SERVICE_ROLE_KEY"
  
  # LLM提供商（至少配置一个）
  ANTHROPIC_API_KEY: "YOUR_ANTHROPIC_API_KEY"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"
  
  # 必需的API密钥
  TAVILY_API_KEY: "YOUR_TAVILY_API_KEY"
  FIRECRAWL_API_KEY: "YOUR_FIRECRAWL_API_KEY"
  RAPID_API_KEY: "YOUR_RAPID_API_KEY"
  DAYTONA_API_KEY: "YOUR_DAYTONA_API_KEY"
  
  # 安全配置
  MCP_CREDENTIAL_ENCRYPTION_KEY: "YOUR_GENERATED_FERNET_KEY"
  TRIGGER_WEBHOOK_SECRET: "YOUR_RANDOM_SECRET"
  
  # 可选：监控
  LANGFUSE_PUBLIC_KEY: "YOUR_LANGFUSE_PUBLIC_KEY"
  LANGFUSE_SECRET_KEY: "YOUR_LANGFUSE_SECRET_KEY"